### ISSUE TITLE
How to build python binding in an Anaconda environment?

### ISSUE THREAD

**Issue by xueeinstein** [simonzhang00/ripser-plusplus#2]
I am trying to use Ripser++ in an anaconda environment. All the test cases passed after built the C++ version. However, when I install the using `source install_w_python_bindings.sh`, it raised errors like:

```
.../x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/type_traits(2953): error: "constexpr" is not valid here
...
...error: "is_pod_v" is not a function or static data member
```

Could you please take a look? To be sure that it is not a common problem, I cannot find similar issues on Stackoverflow :(.

**Comment by simonzhang00** [comment]
Hi Bill,

My guess is your versions of gcc and nvcc are off. I think I use gcc
version ==8.4.0 and nvcc version ==10.1. In case you just need to run ripser++, I have a [gist](https://github.com/simonzhang00/ripser-plusplus/issues/1) in another issue on how to use ripser++ in Google Colab (which runs on cloud instead of on your local machine).


Thanks,
Simon Zhang

**Comment by xueeinstein** [comment]
Hi Simon,

Thanks for your help! My nvcc version is 10.0. I happened to find that gcc 4.8.2 works for me. While gcc 7.3.0 seems not compatible with nvcc 10.0.
